name: CI/CD Pipeline - Prod
run-name: MLOps with Dagster and MLflow

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod
env:
  DB_FLAG: CI

jobs:
  DeployProd:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Set up Python 3.9 environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Model building and testing
      - name: Build and Test Model
        run: echo "Building and testing the model"

      # Run the ML pipeline
      - name: Run ML pipeline
        run: echo "Running the ML pipeline"
